//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Storage2.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Storage2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте правильность параметров подключения.
        /// </summary>
        internal static string InvalidConnection {
            get {
                return ResourceManager.GetString("InvalidConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение не было установлено,
        ///проверьте правильность параметров подкючения
        ///и повторите попытку..
        /// </summary>
        internal static string NoMadeConnection {
            get {
                return ResourceManager.GetString("NoMadeConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенная страка не представляет десятичную дробь.
        /// </summary>
        internal static string NotDecimal {
            get {
                return ResourceManager.GetString("NotDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка добавления.
        ///Проверьте правильность введенных данных
        ///и отсутствие дублирующихся записей
        ///в уникальные столбцы таблицы.
        /// </summary>
        internal static string NotUnique {
            get {
                return ResourceManager.GetString("NotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одно из полей было пусто.
        ///Проверьте, ввели ли Вы
        ///Все необходимые данные..
        /// </summary>
        internal static string NullField {
            get {
                return ResourceManager.GetString("NullField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на -- phpMyAdmin SQL Dump
        ///-- version 4.9.2
        ///-- https://www.phpmyadmin.net/
        ///--
        ///-- Хост: 127.0.0.1:3308
        ///-- Время создания: Дек 10 2021 г., 07:50
        ///-- Версия сервера: 8.0.18
        ///-- Версия PHP: 7.3.12
        ///
        ///SET SQL_MODE = &quot;NO_AUTO_VALUE_ON_ZERO&quot;;
        ///SET AUTOCOMMIT = 0;
        ///START TRANSACTION;
        ///SET time_zone = &quot;+00:00&quot;;
        ///
        ///
        ////*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
        ////*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
        ////*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
        ////*!40101 SET NAME [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SqlRestore {
            get {
                return ResourceManager.GetString("SqlRestore", resourceCulture);
            }
        }
    }
}
